language: python

matrix:
  include:
  - python: '3.6'
  #  env: UPLOAD_M3U=yes
  - python: '3.7-dev'
  allow_failures:
  - python: '3.7-dev'

before_install:
  - pip install --upgrade pip setuptools
  - pip install -r requirements-dev.txt
  - if [[ $UPLOAD_M3U == 'yes' ]]; then
      pip install doctr;
    fi

install:
  - pip install -e .

script:
  - pytest --cov

after_success:
  - set -e
  - if [[ $UPLOAD_M3U == 'yes' && $TRAVIS_REPO_SLUG == 'back-to/iptv' ]]; then doctr deploy iptv; fi

doctr:
  build-tags: True
  deploy-repo: liveproxy/liveproxy.github.io
  key-path: deploy_key_doctr.enc
  require-master: True
  built-docs: playlist/
