language: python

matrix:
  include:
  - python: '3.6'
  - python: '3.7-dev'
  allow_failures:
  - python: '3.7-dev'

script:
  - python run.py --config config/de.cfg
  - python run.py --config config/fr.cfg
  - python run.py --config config/gb.cfg
  - python run.py --config config/ru.cfg
  - python run.py --config config/tr.cfg
  - python run.py --config config/vn.cfg
