language: python

matrix:
  include:
  - python: '3.6'
    env: UPLOAD_M3U=yes
  - python: '3.7-dev'
  allow_failures:
  - python: '3.7-dev'

before_install:
  - pip install --upgrade pip setuptools
  - pip install git+https://github.com/seznam/python-fastjsonschema.git
  - pip install -r requirements-dev.txt
  - if [[ $UPLOAD_M3U == 'yes' ]]; then
      pip install doctr;
    fi
  - mkdir playlist

install:
  - pip install -e .

script:
  - pytest --cov
  - iptv m3u --output playlist/de.m3u --group-country --limit-mirror 2 --name-netloc --source-language 'deu'
  - iptv m3u --output playlist/fr.m3u --group-country --limit-mirror 2 --name-netloc --source-language 'fra'
  - iptv m3u --output playlist/gb.m3u --group-country --limit-mirror 2 --name-netloc --source-language 'eng'
  - iptv m3u --output playlist/ru.m3u --group-country --limit-mirror 2 --name-netloc --source-language 'rus'
  - iptv m3u --output playlist/tr.m3u --group-country --limit-mirror 2 --name-netloc --source-language 'tur'
  - iptv m3u --output playlist/vn.m3u --group-country --limit-mirror 2 --name-netloc --source-language 'vie'
  # --only-direct
  - iptv m3u --output playlist/de_direct.m3u --group-country --limit-mirror 2 --name-netloc --source-language 'deu' --only-direct
  - iptv m3u --output playlist/fr_direct.m3u --group-country --limit-mirror 2 --name-netloc --source-language 'fra' --only-direct
  - iptv m3u --output playlist/gb_direct.m3u --group-country --limit-mirror 2 --name-netloc --source-language 'eng' --only-direct
  - iptv m3u --output playlist/ru_direct.m3u --group-country --limit-mirror 2 --name-netloc --source-language 'rus' --only-direct
  - iptv m3u --output playlist/tr_direct.m3u --group-country --limit-mirror 2 --name-netloc --source-language 'tur' --only-direct
  - iptv m3u --output playlist/vn_direct.m3u --group-country --limit-mirror 2 --name-netloc --source-language 'vie' --only-direct

after_success:
  - set -e
  - if [[ $UPLOAD_M3U == 'yes' && $TRAVIS_REPO_SLUG == 'back-to/iptv' ]]; then doctr deploy iptv; fi

doctr:
  build-tags: True
  deploy-repo: liveproxy/liveproxy.github.io
  key-path: deploy_key_doctr.enc
  require-master: True
  built-docs: playlist/
